name: voxiloud
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  flutter_lints: ^4.0.0
  provider: ^6.1.2
  translator: ^1.0.0
  connectivity_plus: ^6.0.3
  language_detector: ^1.0.0
  flutter_typeahead: ^5.2.0
  iconsax: ^0.0.8
  share_plus: ^9.0.0
  file_picker: ^8.0.3
  open_file: ^3.3.2
  docx_to_text: ^1.0.1
  read_pdf_text: ^0.2.1
  flutter_tts: ^4.0.2
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  flutter_colorpicker: ^1.1.0
  google_mobile_ads: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
